Windows Error

diff --git a/.github/workflows/analyze.yml b/.github/workflows/analyze.yml
--- a/.github/workflows/analyze.yml
+++ b/.github/workflows/analyze.yml
@@ -1,6 +1,10 @@
+# Version with Windows Error
+
 name: analyze
 
-on: push
+on: 
+  push:
+    branches: [datarefinement]
   
 jobs:
   job_matrix:
@@ -11,21 +15,23 @@ jobs:
         os:
           - ubuntu-latest
           - macos-latest
+        experimental: [false] # Standardmäßig kein Job ist experimentell
         version: ["3.12", "3.13"]
         include:
           # Fügt NUR diese eine spezielle Kombination hinzu
           - os: windows-latest
             version: "3.11"
             experimental: true 
+
+    continue-on-error: ${{ matrix.experimental }} # Nur der Windows-Job darf fehlschlage
+    container: 
+      image: python:3.14-slim
     steps:
       - name: checkout-repo
         uses: actions/checkout@v4
 
-      - name: setup-python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.version }}
-          cache: 'pip' # Spart Zeit bei Folge-Runs
+      - name: test-python-version
+        run: python3 --version
 
       - name: install dependencies
         run: |
@@ -35,3 +41,53 @@ jobs:
 
       - name: run-tests
         run: pytest -v
+
+      - name: Spezieller Windows Check
+        if: matrix.os == 'windows-latest'
+        run: |
+          echo "Windows Error"
+          exit 1  # Erzeugt einen Fehler-Statuscode
+
+
+# name: analyze
+
+# on: 
+#   push:
+#     branches: [datarefinement]
+  
+# jobs:
+#   job_matrix:
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       fail-fast: false # Alle 4 Jobs laufen durch, egal ob einer crasht
+#       matrix:
+#         os:
+#           - ubuntu-latest
+#           - macos-latest
+#         experimental: [false] # Standardmäßig kein Job ist experimentell
+#         version: ["3.12", "3.13"]
+#         include:
+#           # Fügt NUR diese eine spezielle Kombination hinzu
+#           - os: windows-latest
+#             version: "3.11"
+#             experimental: true 
+
+#     continue-on-error: ${{ matrix.experimental }} # Nur der Windows-Job darf fehlschlage
+#     steps:
+#       - name: checkout-repo
+#         uses: actions/checkout@v4
+
+#       - name: setup-python
+#         uses: actions/setup-python@v5
+#         with:
+#           python-version: ${{ matrix.version }}
+#           cache: 'pip' # Spart Zeit bei Folge-Runs
+
+#       - name: install dependencies
+#         run: |
+#           pip install --upgrade pip
+#           pip install pytest
+#           pip install numpy matplotlib pandas
+
+#       - name: run-tests
+#         run: pytest -v
